### PR TITLE
Support tests on C++ std::string

### PR DESCRIPTION
**Pull request by tekknolagi**
This is helpful for C++ projects.

### CODE REVIEW

**Comment by tekknolagi** [comment]
In any case, thank you very much for this project :)

**Comment by sheredom** [comment]
The issue is that pre C++11 didn't have auto, and so the `UTEST_AUTO` macro is going back to the C version which uses `typeof`. I needed to do `typeof(x + 0)` to force type resolution (painful, horrific, but works!). I guess if you only added the test to https://github.com/sheredom/utest.h/blob/master/test/test11.cpp it'd work.

**Comment by tekknolagi** [comment]
Oh! This is... fascinating. I will take a look at doing that. Thank you.

**Comment by tekknolagi** [comment]
Huh. Not sure what is going on with Windows.

**Pull request closed without merging**
