### PR TITLE
Add test exception with message

### PR DESCRIPTION
**Pull request by facug91**
Solves issue #130

### CODE REVIEW

**Comment by facug91** [comment]
I tested this on Ubuntu 20 and it worked fine. I seem to be missing something for Windows :sweat_smile:. Sorry, I'll check this out later.

**Comment by sheredom** [comment]
Windows seems fine - but there is some UBSAN issue.

**Comment by facug91** [comment]
In my computer the sanitizer is failing even in master. In the CI it is failing with `use-of-uninitialized-value`, but I just added `message_caught` which is initialized with the value `UTEST_NULL`, and `message_size` which is initialized with `strlen(e.what()) + 1`. I can't find the problem.
I've been reading on stackoverflow that MemorySanitizer sometimes returns false positives for this, but I'm not sure this is the case. Can you help me please @sheredom? I am a bit lost.

**Comment by sheredom** [comment]
Trying to work this out at the minute in the other PR (with some choice language, its just for testing as I don't have Linux locally setup at present!) #132

**Comment by facug91** [comment]
I see in your commits in the other PR, that it seems to be a problem with the compiler. I made a commit to disable the test like you did, but only for `test.cpp`, which is the file that was failing here. If I see that it also fails in the others, I will disable it in those files as well. Thank you!

**Comment by sheredom** [comment]
Yeah @facug91 it seems like this is the same GLIBC cstdlib sanitizer bug - pretty hard to track down!

**Comment by sheredom** [comment]
Good work getting this through!

**Pull request merged**
